### ISSUE TITLE
Bug: VOs not deleted after disconnecting from AAI

### ISSUE THREAD

**Issue by andreasfk** [nextcloud/vo_federation#12]
Disconnecting from an AAI does not remove VO memberships or VOs on the Nextcloud Instance.

**Comment by andreasfk** [comment]
Group memberships are now correctly removed after unlinking the AAI, however, the VO-related groups themselves should also be removed from the instance if they have no remaining members.

**Comment by smesterheide** [comment]
Thanks for the bug report. Please take a look and see if it works as expected in v0.1.0

**Comment by smesterheide** [comment]
> Group memberships are now correctly removed after unlinking the AAI, however, the VO-related groups themselves should also be removed from the instance if they have no remaining members.

Ack'd that VO-related groups remain and needs fixing

**Comment by andreasfk** [comment]
Issue is fixed.
