### ISSUE TITLE
Bug: Certificate error on share with Helmholtz-member VO

### ISSUE THREAD

**Issue by andreasfk** [nextcloud/vo_federation#13]
Sharing with the VO "Helmholtz-member" causes the following certificate error: 
> Fehler beim Erstellen der Freigabe: Sharing Vorlagen failed, could not find urn:geant:helmholtz.de:group:Helmholtz-member#login-dev.helmholtz.de@https://nc1.nextcloud.test.publicplan.cloud, maybe the server is currently unreachable or uses a self-signed certificate."

No share is created after the error is displayed.

**Comment by smesterheide** [comment]
This is a generic failure when the share cannot be created on the remote server. I will address this in several ways:
- Give proper error message when the cause of the failure is not SSL related
- Move to asynchronous remote sharing with retries as a background job
- Make sure the operation continues if one or more servers are unavailable

**Comment by andreasfk** [comment]
But why would it happen for this one VO in particular?

**Comment by smesterheide** [comment]
It may also be that the server does not accept incoming remote group shares (4th switch from top). The config is shared between remote group shares and federated group shares.
![grafik](https://user-images.githubusercontent.com/1752390/205892696-e748e4ae-9c2a-4aeb-a9ad-a521f6bb5f4f.png)

Otherwise please recreate the share on the test system and I will look into it.

**Comment by andreasfk** [comment]
I'm not sure why, but the bug does not occure in 0.1.3 anymore.

**Comment by smesterheide** [comment]
> I'm not sure why, but the bug does not occur in 0.1.3 anymore.

Maybe it still occured but the share was shared with multiple VOs and the user that accepted the share on the receiving instance was part of more than one group?

**Comment by andreasfk** [comment]
As it occured on the Sharer's side, this would probably not be cause of the issue. I'm still clueless.

**Comment by smesterheide** [comment]
The DB migration is now part of the server-side pull request and hotfixed on the test server. If the error occurs agains please reopen the ticket.
