### ISSUE TITLE
Bug: Permissions to create files within folders

### ISSUE THREAD

**Issue by andreasfk** [nextcloud/vo_federation#14]
Sharing of a folder with default permissions will allow the sharee to create files within the shared folder, however, they receive the error message "cannot be created". The file will then be visible for the sharee, but not for the sarer.

**Comment by smesterheide** [comment]
>  The file will then be visible for the sharee, but not for the sarer.

Is the sharee the one who was initially receiving the folder share by the sharer?

**Comment by andreasfk** [comment]
It seems that I cannot recreate this bug in version 0.1.0.

We will do some further testing later this week.

**Comment by andreasfk** [comment]
Issue is fixed.
