### ISSUE TITLE
Bug: displaying created shares correctly

### ISSUE THREAD

**Issue by andreasfk** [nextcloud/vo_federation#15]
After sharing, the sharer does not see the file as shared in the Files-App default view, only in the detail view. After refreshing, the share is displayed twice in the detail view.

It actually seems to have created another share-like object, not just a duplicate display of the same share: When changing permissions in one of the displayed identical shares, the permissions are only changed within the one where they have been changed. When unsharing after changing permissions, only one of the displayed shares will be removed.

Unsharing one of the displayed shares will properly remove folders on the sharee side, but not files.

**Comment by smesterheide** [comment]
> After sharing, the sharer does not see the file as shared in the Files-App default view, only in the detail view.
I can confirm the label `Shared` is missing in the default view.

> It actually seems to have created another share-like object, not just a duplicate display of the same share
That is in fact what is happening. Each target instance is recognized as an individual share-object. They should be displayed as one and changes to one share-objects update should be reflected on all share-objects. Also for the user all share-objects should be collapsed into one entry. This is however difficult for the local group share as it is of a different share type.

> Unsharing one of the displayed shares will properly remove folders on the sharee side, but not files.
Thanks for the test case. Folders require special handling. I will analyze this further.

I see probably three distinct bugs here.

**Comment by andreasfk** [comment]
Issue is fixed.
