### ISSUE TITLE
Bug: VOs no longer displayed for user

### ISSUE THREAD

**Issue by andreasfk** [nextcloud/vo_federation#18]
Maybe relevant: Have been added to new VO by admin in AAI (ergo: attributes have changed).

Logging out and back in seemingly removes all VO memberships for users. 
Logging back out/in or disconnecting/connecting with AAI does not bring VOs back.

Existing shares remain available for users.
Ability to share with VOs remains from sharer perspective, but remote users do not receive share.

**Comment by smesterheide** [comment]
Probably caused by OIDC misconfiguration that has since been corrected. Please log out and back in to see if problem is fixed.
