### ISSUE TITLE
Bug: Unshare removes permission but the share will continue to be created on Sharee side

### ISSUE THREAD

**Issue by andreasfk** [nextcloud/vo_federation#31]
After unsharing as sharer, the sharee will correctly lose permissions to the folder. However, it will not me removed from the files view unless they try to access it. After the permission denied error message appeared, the share will be removed from the files app. However, it will continuously be recreated after each refresh of the files app.

**Comment by andreasfk** [comment]
Might be the case that the behaviour only persists until cron jobs on local and/or remote instance were executed.

**Comment by smesterheide** [comment]
I tested un-sharing in v0.3.3 of accepted and unaccepted VO shares. The file view on the sharee side is now in sync with the actual share state.

**Comment by andreasfk** [comment]
Sadly, I cannot confirm this. The share is still visible on sharee side after the sharer unshares. Accessing it still removes the share, which is then recreated on refresh of the files app.

**Comment by andreasfk** [comment]
Bug is actually fixed or never really existed in the first place. The behaviour is caused by the asynchrous cron-job mechanic which is used to queue share information update on sharing as well as unsharing.

In future iterations of the software we will hopefully find a way to remain asynchronous but in a faster manner than using the default cron job.
